(ns cleavage.core
  (:use [penumbra opengl]
	[clojure.java.io])
  (:require [penumbra.app :as app]
	    [clojure.string :as str]
	    [clojure.contrib.strint :as strint])
  (:import (org.eclipse.jgit.lib Repository RepositoryBuilder Constants)
	   (org.eclipse.jgit.revwalk RevCommit RevWalk)
	   (org.eclipse.jgit.treewalk.filter PathFilter TreeFilter AndTreeFilter)))

(def *git-victimdir* "/Users/alex/mongo-java-driver/")

(defn victimdir
  "returns the directory to be analyzed by cleavage"
  []
  (file *git-victimdir*))

(defn repository
  "a JGit Repository instance generated by readings *git-victimdir*"
  []
  (.. (RepositoryBuilder.) (findGitDir (victimdir)) (build)))

(defn relative-path
  [file]
  (str/replace (.getPath file) *git-victimdir* ""))

(defn repository-resolve
  [revision]
  (.resolve (repository) revision))

(defn commit-count
  "a count of all the commits touching a specific file"
  [file revsision]
  (let [rw (RevWalk. (repository))]
    (.markStart rw (.parseCommit rw (repository-resolve revsision)))
    (.setTreeFilter rw (AndTreeFilter/create (PathFilter/create (relative-path file)) TreeFilter/ANY_DIFF))
    (count (seq rw))))

(defn victim-files
  "returns lazyseq of all the files in victimdir"
  []
  (filter
   #(re-find (re-pattern "\\.java$")
	     (.getName %1))
   (file-seq (victimdir))))

(defn cyclomatches
  [contents]
  (count (re-seq #"for|if|while|case|catch|&&|\\\|\\\||\\\?" contents)))

(defn cyclomatic-complexity
  "returns the cyclomatic complexity for one file"
  [contents]
  (cyclomatches contents))

(defn complexity
  "returns a numeric complexity score for some file"
  [contents]
  (cyclomatic-complexity contents))

(defn revision-contents
  [file revision]
  (let [resolve-query (strint/<< "~{revision}:~(relative-path file)")
	versioned-object-id (repository-resolve resolve-query)]
    (if (nil? versioned-object-id)
      ""
      (slurp (.. (repository) (open versioned-object-id) openStream)))))

(defn scatter-point
  [file revision]
  (vector (relative-path file) (complexity (revision-contents file revision)) (commit-count file revision)))

(defn scatter-plot
  [revision]
  (map #(scatter-point %1 revision) (victim-files)))


